addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb

after_success:
  - pip install coveralls
  - coveralls

stages:
  - lint
  - test
  - name: deploy
    if:
      tag IS present AND repo = brainglobe/brainreg-segment

jobs:
  include:
    - stage: lint
      name: "Lint"
      language: python
      os: linux
      dist: bionic
      python: 3.7
      script: bash travis/lint.sh
    - stage: test
      name: "Ubuntu Bionic python 3.6"
      language: python
      os: linux
      dist: bionic
      python: 3.6
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: test
      name: "Ubuntu Bionic python 3.7"
      language: python
      os: linux
      dist: bionic
      python: 3.7
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: test
      name: "Ubuntu Xenial python 3.7"
      language: python
      os: linux
      dist: xenial
      python: 3.7
      script: travis_wait 40 bash travis/install_test_linux.sh
    - stage: deploy
      os: bionic
      name: "Deploy Linux"
      language: python
      script: bash travis/deploy_linux.sh
notifications:
  email:
    recipients:
    - adam.tyson@ucl.ac.uk
    on_success: change
    on_failure: always

env:
  global:
    - TWINE_USERNAME=__token__
    # TWINE_PASSWORD is set to a PyPI API token in Travis settings