# Constants used throughout
WINDOW_HEIGHT = 750
WINDOW_WIDTH = 1500
COLUMN_WIDTH = 150


POINT_SIZE = 5
SPLINE_SIZE = 4
NUM_COLORS = 10
BRUSH_SIZE = 10
SPLINE_POINTS_DEFAULT = 1000
SPLINE_SMOOTHING_DEFAULT = 0.1
FIT_DEGREE_DEFAULT = 3

SUMMARISE_TRACK_DEFAULT = True
ADD_SURFACE_POINT_DEFAULT = False
CALCULATE_VOLUMES_DEFAULT = True
SUMMARIZE_VOLUMES_DEFAULT = True

TRACK_FILE_EXT = ".points"
IMAGE_FILE_EXT = ".tiff"
BOUNDARIES_STRING = "Boundaries"
